[electrum] fix NameError in keepkey.py
Summary:
While trying to run pytest, I noticed this error. It is caused by `Transaction` being used in a typehint while not actually being imported. Enable postponed evaluation of annotations to fix this.

```
NameError: name 'Transaction' is not defined
```

Test Plan: `python -m electrumabc_plugins.keepkey.keepkey`

Reviewers: #bitcoin_abc, Fabien

Reviewed By: #bitcoin_abc, Fabien

Differential Revision: https://reviews.bitcoinabc.org/D14468