[backport#17999 2/2] refactor: Use psbt forward declaration
Summary:
Also clean up forward other forward declarations in interfaces/wallet.h with !sort

Original motivation for this change was to fix a circular dependencies lint
error: "interfaces/chain.h -> interfaces/wallet.h -> psbt -> node/transaction
-> node/context -> interfaces/chain.h" from an earlier commit in this PR adding
a "interfaces/chain.h -> interfaces/wallet.h" include. Now, the wallet include
is no longer added, but it is still good to clean up the psbt include for
efficiency, and to sort the forward declarations.

---
Depends on D6995

Backport of Core [[https://github.com/bitcoin/bitcoin/pull/17999 | PR17999]] part [2/2] : https://github.com/bitcoin/bitcoin/pull/17999/commits/3ce16ad2f91d1e2edc7e7bdc5a19f72aa8c3e739

Test Plan:
  ninja all check check-functional

Reviewers: #bitcoin_abc, deadalnix

Reviewed By: #bitcoin_abc, deadalnix

Differential Revision: https://reviews.bitcoinabc.org/D7962