[secp256k1] cmake: disable C extensions
Summary:
D19483 causes the OSX guix build to fail with error

```
[12:15:37] :	 [Step 2/2] /gnu/store/zvlp3n8iwa1svxmwv4q22pv1pb1c9pjq-glibc-2.39/include/bits/local_lim.h:38:10: fatal error: 'linux/limits.h' file not found
[12:15:37] :	 [Step 2/2]    38 | #include <linux/limits.h>
[12:15:37] :	 [Step 2/2]       |          ^~~~~~~~~~~~~~~~
[12:15:37] :	 [Step 2/2] 1 error generated.
```

Disabling C extensions seems to fix that.

Test Plan: `HOSTS="x86_64-apple-darwin" contrib/guix/guix-build`

Reviewers: #bitcoin_abc, Fabien

Reviewed By: #bitcoin_abc, Fabien

Differential Revision: https://reviews.bitcoinabc.org/D19632