guix: disable libsanitizer in Linux GCC build
Summary:
This causes issues when building against newer glibcs (i.e 2.42), and isn't needed
in any case.

```bash
../../../../gcc-14.3.0/libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cpp:483:31: error: invalid application of ‘sizeof’ to incomplete type ‘__sanitizer::termio’
  483 |   unsigned struct_termio_sz = sizeof(struct termio);
      |                               ^~~~~~~~~~~~~~~~~~~~~
```

Extracted from #25573.

This is a backport of [[https://github.com/bitcoin/bitcoin/pull/33780 | core#33780]]
Depends on D20559

Test Plan: guix builds

Reviewers: #bitcoin_abc, Fabien

Reviewed By: #bitcoin_abc, Fabien

Differential Revision: https://reviews.bitcoinabc.org/D20562