[cmake] Properly include public BerkeleyDB headers with wallet library
Summary:
Fixes the following compilation issue on MacOS X:

```
FAILED: src/CMakeFiles/server.dir/init.cpp.o
ccache /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DHAVE_CONFIG_H -DLEVELDB_PLATFORM_POSIX -DOS_MACOSX -I../src/leveldb/helpers/memenv -isystem /usr/local/include -I../src/. -Isrc -I../src/univalue/include -Isrc/crypto/.. -I../src/secp256k1/include -I../src/leveldb/include -Isrc/leveldb/include -Wall -Wextra -Wformat -Wvla -Wformat-security -Wcast-align -Wunused-parameter -Wno-unused-parameter -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -fvisibility=hidden   -std=gnu++11 -MD -MT src/CMakeFiles/server.dir/init.cpp.o -MF src/CMakeFiles/server.dir/init.cpp.o.d -o src/CMakeFiles/server.dir/init.cpp.o -c ../src/init.cpp
In file included from ../src/init.cpp:46:
In file included from ../src/./wallet/wallet.h:19:
In file included from ../src/./wallet/walletdb.h:14:
../src/./wallet/db.h:21:10: fatal error: 'db_cxx.h' file not found
#include <db_cxx.h>
         ^~~~~~~~~~
1 error generated.
```

Test Plan: Run cmake

Reviewers: #bitcoin_abc, deadalnix

Reviewed By: #bitcoin_abc, deadalnix

Subscribers: deadalnix, teamcity

Differential Revision: https://reviews.bitcoinabc.org/D1341