Merge #13500: [wallet] Decouple wallet version from client version
Summary:
cd3f4aa80810fc077c7f9528a4ef53c1438c86e1 Decouple wallet version from client version (Andrew Chow)

Pull request description:

  Instead of comparing version numbers in the wallet to the client version number, compare them to the latest supported wallet version in the client. This allows for wallet version numbers to be unrelated to the client version number.

Tree-SHA512: 69c3e1f45a40bde01d622d504a803fea32fc14e2e27b14b0729725349d8592d56ebca26fd06f117fd6f5164fb4ce980122751b6370f6e25f1a947dbdf4143ddd

Backport of Core PR13500
https://github.com/bitcoin/bitcoin/pull/13500/

Test Plan:
  make check
  ./bitcoind
Edit wallet/wallet.h line 94 from
  FEATURE_LATEST = FEATURE_PRE_SPLIT_KEYPOOL,
to
  FEATURE_LATEST = FEATURE_BASE,
Ensure `bitcoind` crashes with the following error:
  2019-12-10T20:45:15Z Error: Error loading : Wallet requires newer version of Bitcoin ABC
  Error: Error loading : Wallet requires newer version of Bitcoin ABC

Reviewers: deadalnix, Fabien, jasonbcox, O1 Bitcoin ABC, #bitcoin_abc

Reviewed By: Fabien, O1 Bitcoin ABC, #bitcoin_abc

Differential Revision: https://reviews.bitcoinabc.org/D4689