[chronik] fix ChronikBridge::load_raw_tx and compress_script
Summary:
This fixes a compilation error in chronik_bridge
```
/home/pierre/dev/bitcoin-abc/chronik/chronik-cpp/chronik_bridge.cpp:240:45:   required from here
/usr/include/c++/11/bits/stl_algobase.h:385:25: error: no match for ‘operator=’ (operand types are ‘std::back_insert_iterator<rust::cxxbridge1::Vec<unsigned char> >’ and ‘const std::byte’)
```

I broke these functions in D15935. The underlying data type for CDataStream is now std::byte instead of `uint8_t`, so we need to cast the streams before passing them to `chronik::util::ToRustVec<uint8_t>`

Depends on D15943

Test Plan:
```
 cmake .. -GNinja  -DBUILD_BITCOIN_CHRONIK=ON
ninja all check-all
```

Reviewers: #bitcoin_abc, Fabien

Reviewed By: #bitcoin_abc, Fabien

Subscribers: Fabien

Differential Revision: https://reviews.bitcoinabc.org/D15948