[backport#19299] remove unused variables and add missing includes
Summary:
fa09ec83f3f23dacb807c6b6393cabf2a984e4ff
> Remove unused variables

fa193c6b1b7da8f72a399bfddb1497655ce1685c
> Add missing includes to fix compile errors
>
> fs.cpp:35:17: error: no member named 'strerror' in namespace 'std'
>     return std::strerror(errno);
>            ~~~~~^
> fs.cpp:49:9: error: use of undeclared identifier 'close'
>         close(fd);
>         ^
> 2 errors generated.i

This is a backport of [[https://github.com/bitcoin/bitcoin/pull/19299 | core#19299]]

Test Plan: `ninja all check-all`

Reviewers: #bitcoin_abc, deadalnix

Reviewed By: #bitcoin_abc, deadalnix

Differential Revision: https://reviews.bitcoinabc.org/D9429