scripts: rename test_64bit_PE to test_PE
Summary:
This is a backport of [[https://github.com/bitcoin/bitcoin/pull/18415 | core#18415]]
https://github.com/bitcoin/bitcoin/pull/18415/commits/7142d50ac33e0ad7d24e49e04c1fc7e3e769ed46

Depends on D13552

Test Plan:
I ran this test locally, but it fails for reasons unrelated to this diff (same on master)
```
FAIL: test_PE (__main__.TestSecurityChecks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pierre/dev/bitcoin-abc/contrib/devtools/./test-security-check.py", line 56, in test_PE
    self.assertEqual(call_security_check(cc, source, executable, ['-Wl,--no-nxcompat', '-Wl,--no-dynamicbase', '-Wl,--no-high-entropy-va', '-no-pie', '-fno-PIE']),
AssertionError: Tuples differ: (1, 'test1.exe: failed DYNAMIC_BASE HIGH_ENTROPY_VA NX') != (1, 'test1.exe: failed DYNAMIC_BASE HIGH_ENTROPY_VA NX RELOC_SECTION')

First differing element 1:
'test1.exe: failed DYNAMIC_BASE HIGH_ENTROPY_VA NX'
'test1.exe: failed DYNAMIC_BASE HIGH_ENTROPY_VA NX RELOC_SECTION'

- (1, 'test1.exe: failed DYNAMIC_BASE HIGH_ENTROPY_VA NX')
+ (1, 'test1.exe: failed DYNAMIC_BASE HIGH_ENTROPY_VA NX RELOC_SECTION')
?                                                       ++++++++++++++
```

Just check that the test still runs (and fails) after the renaming.

Reviewers: #bitcoin_abc, Fabien

Reviewed By: #bitcoin_abc, Fabien

Differential Revision: https://reviews.bitcoinabc.org/D13553