build, qt: backport patches
Summary:
This brings us to the same set of patches as the current tip of the Core repository, minus the ones for architectures we don't support (mainly android and arm64 MacOS)

> build, qt: Hardcode last modified timestamp in Qt RCC
>
> This change allows the already built qt package to be reused even with
> the SOURCE_DATE_EPOCH variable set, e.g., for Guix builds.

> build: patch around qt duplicate symbol issue
>
> This is currently causing the same failure in two different PRs:
> ```bash
> duplicate symbol 'lcQpaFonts()' in:
>     /tmp/cirrus-ci-build/depends/x86_64-apple-darwin/lib/libQt5ThemeSupport.a(qgenericunixthemes.o)
>     /tmp/cirrus-ci-build/depends/x86_64-apple-darwin/lib/libQt5FontDatabaseSupport.a(qfontengine_coretext.o)
> ld: 1 duplicate symbol for architecture x86_64
> ```
>
> ```bash
> x86_64-apple-darwin-ld: error: duplicate symbol: __Z10lcQpaFontsv
> >>> defined in /tmp/cirrus-ci-build/depends/x86_64-apple-darwin/lib/libQt5ThemeSupport.a(qgenericunixthemes.o)
> >>> defined in /tmp/cirrus-ci-build/depends/x86_64-apple-darwin/lib/libQt5FontDatabaseSupport.a(qfontengine_coretext.o)
> ```
>
> Co-authored-by: Hennadii Stepanov <32963518+hebasto@users.noreply.github.com>
>

> depends: modify FastFixedDtoa optimisation flags
>
> This fixes a non-determinism issue in the asm produced for
> this function when cross-compiling on x86_64 and aarch64 for
> the arm-linux-gnueabihf HOST.
>
> Related to #21194.

> guix: More thoroughly control native toolchain

This patch has been updated (line numbers in the diff only)  to account for a Qt version bump (D13918)

This is a backport of [[https://github.com/bitcoin/bitcoin/pull/23862 | core#23862]], [[https://github.com/bitcoin/bitcoin/pull/24722 | core#24722]] and [[https://github.com/bitcoin/bitcoin/pull/25643 | core#25643]]

and https://github.com/bitcoin/bitcoin/pull/21375/commits/c1ae726a13ecfa5e7e9fdc3030a8110b8bb263f8

Depends on D13926

Test Plan: local crossbuild of qt, gitian builds, guix build

Reviewers: #bitcoin_abc, Fabien

Reviewed By: #bitcoin_abc, Fabien

Differential Revision: https://reviews.bitcoinabc.org/D13927