Fix missing header in sync.h
Summary:
> std::string is referenced in sync.h but the relevant header is not explicitly included as required by current guideline. Furthermore on osx 10.14.6 with clang-900.0.31 the following error occurs:
>
> ```
> In file included from threadinterrupt.cpp:6:
> In file included from ./threadinterrupt.h:8:
> ./sync.h:206:21: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
>         std::string lockname;
> ```

This is a backport of Core [[https://github.com/bitcoin/bitcoin/pull/18357 | PR18357]]

Test Plan: `ninja`

Reviewers: #bitcoin_abc, Fabien

Reviewed By: #bitcoin_abc, Fabien

Differential Revision: https://reviews.bitcoinabc.org/D8843