http: add missing header bootlegged by boost < 1.72
Summary:
```
httpserver.cpp:74:10: error: no template named 'deque' in namespace
'std'
    std::deque<std::unique_ptr<WorkItem>> queue;
    ~~~~~^
```

Backport of core [[https://github.com/bitcoin/bitcoin/pull/17249/files | PR17249]].

Fixes the build on ArchLinux.

Test Plan:
  ninja check
  make check

Reviewers: #bitcoin_abc, markblundeberg

Reviewed By: #bitcoin_abc, markblundeberg

Differential Revision: https://reviews.bitcoinabc.org/D5161