depends: backport updates for libevent.mk
Summary:
> depends: use FORTIFY_SOURCE=3 with libevent
[[https://github.com/bitcoin/bitcoin/pull/27118 | core#27118]]

------

> depends: switch libevent to CMake

[[https://github.com/bitcoin/bitcoin/pull/29835 | core#29835]]
[[https://github.com/bitcoin/bitcoin/pull/30488 | core#30488]]
https://github.com/bitcoin/bitcoin/pull/30506/changes/06d4aab77af4e75f0e8fd96a93e108f92210d878

------

> depends: build libevent with -D_GNU_SOURCE
>
> Currently, builds of libevent in depends, using CMake, fail on some
> systems, like Alpine, with the following:
> ```bash
> /bitcoin/depends/work/build/aarch64-unknown-linux-musl/libevent/2.1.12-stable-1516ed47ea8/evmap.c: In function 'evmap_signal_add_':
> /bitcoin/depends/work/build/aarch64-unknown-linux-musl/libevent/2.1.12-stable-1516ed47ea8/evmap.c:456:31: error: 'NSIG' undeclared (first use in this function)
>   456 |         if (sig < 0 || sig >= NSIG)
> ```
>
> From what I can tell the `_GNU_SOURCE` "detection" in libevents CMake build
> system, never? really worked, and it's not clear what a nice fix is.
>
> For now, always use `_GNU_SOURCE` when building libevent in depends.

[[https://github.com/bitcoin/bitcoin/pull/30743 | core#30743]]

------

> depends: Override default build type for `libevent`
>
> The `libevent` package defaults to the "Release" build type, which
> overrides our per-build-type optimization flags with `-O3`.
>
> To prevent this behavior, set `CMAKE_BUILD_TYPE` to "None", consistent
> with how other packages are handled.

[[https://github.com/bitcoin/bitcoin/pull/31661 | core#31661]]
https://github.com/bitcoin/bitcoin/pull/31800/changes/407062f2ac93624f350e9e8a4f641c882a2aaf2f (partial)

------

> depends: Avoid `warning: "_FORTIFY_SOURCE" redefined` for `libevent`
>
> On Alpine Linux 3.12.3, compiling the `libevent` package produces
> multiple warnings:
> ```
> $ gmake -C depends -j $(nproc) libevent
> <snip>
> <command-line>: warning: "_FORTIFY_SOURCE" redefined
> <built-in>: note: this is the location of the previous definition
> <snip>
> ```

[[https://github.com/bitcoin/bitcoin/pull/32266 | core#32266]]

------

> depends: fix libevent _WIN32_WINNT usage
>
> Starting with version 13.x, the mingw headers will define the value of
> NTDDI_VERSION, based on the value of _WIN32_WINNT, if that version is <
> Windows 10. Given that libevent was undefining our _WIN32_WINNT, and
> redefining it to a value < Windows 10 (0x0501), NTDDI_VERSION was also
> being defined to that value, leading to functions not being exposed in
> the mingw-w64 headers; see here:
> https://github.com/mingw-w64/mingw-w64/blob/9c2668ef77e75ea4d8a6c7d100b14643269caec3/mingw-w64-headers/include/iphlpapi.h#L36-L41.
>
> Imports a commit from usptream (a14ff91254f40cf36e0fee199e26fb11260fab49).

[[https://github.com/bitcoin/bitcoin/pull/32837 | core#32837]]

------

depends, libevent: remove more stuff in postprocess

- Do not install *.pc files and remove patches for them
- prune event2 compat headers:
- don't install deprecated libevent headers (this requires changing FindEvent.cmake to specifically look for the event2/event.h header).

We can't delete "lib/libevent.a" without making FindEvent.cmake fail, and I wasn't able to fix this one.

[[https://github.com/bitcoin/bitcoin/pull/24526 | core#24526]]
[[https://github.com/bitcoin/bitcoin/pull/25918 | core#25918]]
https://github.com/bitcoin/bitcoin/pull/31181/changes/5a96767e3f531ba9e8a676eec47727421f9f589f

------

This is a backport of [[https://github.com/bitcoin/bitcoin/pull/27118 | core#27118]], [[https://github.com/bitcoin/bitcoin/pull/29835 | core#29835]], [[https://github.com/bitcoin/bitcoin/pull/30488 | core#30488]], [[https://github.com/bitcoin/bitcoin/pull/30506 | core#30506]] (partial), [[https://github.com/bitcoin/bitcoin/pull/30743 | core#30743]], [[https://github.com/bitcoin/bitcoin/pull/31661 | core#31661]], [[https://github.com/bitcoin/bitcoin/pull/31800 | core#31800]] (partial), [[https://github.com/bitcoin/bitcoin/pull/32266 | core#32266]], [[https://github.com/bitcoin/bitcoin/pull/32837 | core#32837]], [[https://github.com/bitcoin/bitcoin/pull/24536 | core#24536]], [[https://github.com/bitcoin/bitcoin/pull/25918 | core#25918]] and [[https://github.com/bitcoin/bitcoin/pull/31181 | core#31181]] (partial)

Test Plan: `contrib/guix/guix-build`

Reviewers: #bitcoin_abc, Fabien

Reviewed By: #bitcoin_abc, Fabien

Subscribers: Fabien

Differential Revision: https://reviews.bitcoinabc.org/D19661