tests: Mark functional tests not supporting bitcoin-cli (--usecli) as such
Summary:
The option `--usecli` was added to test_framework in [[https://github.com/bitcoin/bitcoin/pull/11970 | PR11970]]. Running the test with this parameter will cause all RPCs to be sent through `bitcoin-cli` rather than directly over http. But the test were not all annotated accordingly. 74 tests were unnecessarily skipped.

Explicitely annotating the tests that do not support this option will allow to make this lack of support the exception, and identify these tests clearly as needing to be fixed in  the future.

This commit has currently no effect, as `self.supports_cli` is still considered `False` by default. This will be changed in the next commit.

In addition to the tests skipped in the Core PR, I also found the following tests to not support `--usecli`:
- `abc_wallet_standardness`: `TypeError: Object of type 'Decimal' is not JSON serializable` (will be fixed when backporting PR17705)
- `abc-magnetic-anomaly-mining`: idem
- `p2p_blocksonly`: idem
- `rpc_whitelist`: `AttributeError: 'NoneType' object has no attribute 'rfind'` (this test was added after PR17675 and should have been skipped in Core as well)
- `abc_p2p_fullblocktest`: `OSError: [Errno 7] Argument list too long: '.../bitcoin-abc/build/src/bitcoin-cli'`
- `wallet_groups` : idem

This is a backport of Core [[https://github.com/bitcoin/bitcoin/pull/17675 | PR17675]] [1/2]
https://github.com/bitcoin/bitcoin/pull/17675/commits/993e38a4e2fa66093314b988dfbe459f46aa5864

Test Plan: `test/functional/test_runner.py --usecli`

Reviewers: #bitcoin_abc, deadalnix

Reviewed By: #bitcoin_abc, deadalnix

Subscribers: deadalnix

Differential Revision: https://reviews.bitcoinabc.org/D8316