guix: update time-machine
Summary:
> guix: update python-oscrypto to 1.3.0
>
> This is required for bumping the time-machine, for compatibility with
> OpenSSL:
>
> oscrypto: openssl backend, 1.2.1, /tmp/guix-build-python-oscrypto-1.2.1.drv-0/source/oscrypto
> Traceback (most recent call last):
>   File "/tmp/guix-build-python-oscrypto-1.2.1.drv-0/source/oscrypto/_openssl/_libcrypto_ctypes.py", line 304, in <module>
>     libcrypto.EVP_PKEY_size.argtypes = [
>   File "/gnu/store/9dkl9fnidcdpw19ncw5pk0p7dljx7ijb-python-3.10.7/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
>     func = self.__getitem__(name)
>   File "/gnu/store/9dkl9fnidcdpw19ncw5pk0p7dljx7ijb-python-3.10.7/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
>     func = self._FuncPtr((name_or_ordinal, self))
> AttributeError: /gnu/store/2hr7w64zhr6jjznidyc2xi40d5ynhj9c-openssl-3.0.8/lib/libcrypto.so.3: undefined symbol: EVP_PKEY_size. Did you mean: 'EVP_PKEY_free'?

https://github.com/bitcoin/bitcoin/pull/28328/commits/f1a4afb26f21e6e2297616f9f8d1e8fa93be14cf

> guix: update time-machine to 160f78a4d92205df986ed9efcce7d3aac188cb24
>
> In our time-machine environment this changes the following:
>
> GCC 10.3.0 -> 10.4.0
> Binutils 2.37 -> 2.38
> Linux Libre Headers 5.15.37 -> 5.15.127
> git 2.36.0 -> 2.41.0
> mingw-w64 8.0.0 -> 11.0.1
> NSIS 3.05 -> 3.09
> xorriso 1.5.2 -> 1.5.6.pl02
> Python 3.9 -> 3.10.7
> Python-asn1crypto 1.4.0 -> 1.5.1
>
> GCC 12.3.0 becomes available.
> LLVM 15.0.7 becomes available.

https://github.com/bitcoin/bitcoin/pull/28328/commits/ea4387e1d074632d63a25660990d44cae74665b0

> guix: use cross-* keyword arguments
>
> Using the new time-machine results in warnings about consistently using
> keyword arguments:
> ```bash
> guix environment: warning: 'cross-kernel-headers' must be used with keyword arguments
> guix environment: warning: 'cross-libc' must be used with keyword arguments
> ```

https://github.com/bitcoin/bitcoin/pull/28328/commits/1f6c75e82bc97ff08e444f2b0569289e96a42356

> guix: drop NSIS patch now that we use 3.09
>
> See https://sourceforge.net/p/nsis/bugs/1283/.

https://github.com/bitcoin/bitcoin/pull/28328/commits/a1d4a42993b032cb74734d2d728f9baf98673c9e

> guix: drop Windows broken-longjmp.patch
>
> This is no-longer required, now that we are building using GCC 10.4.0.

https://github.com/bitcoin/bitcoin/pull/28328/commits/6cbedc3d9b67538e9949816226ccbe065e4f26a4

> guix: remove GCC 10 workaround from NSIS
>
> Fixed upstream in 3.06, see
> https://github.com/kichik/nsis/commit/229b6136c41ba5caba25936f4927476d20aa283f.
> https://sourceforge.net/p/nsis/bugs/1248/

From the PR discussion:
>  This commit could have gone in with [[https://github.com/bitcoin/bitcoin/pull/28328 | core#28328]]
https://github.com/bitcoin/bitcoin/pull/28370/commits/588068d5a12b752b70bb7e4f3f8decb1ce2fe4e8

This is a backport of [[https://github.com/bitcoin/bitcoin/pull/28328 | core#28328]] and [[https://github.com/bitcoin/bitcoin/pull/28370 | core#28370]]
Depends on D15488

Test Plan: `contrib/guix/guix-build`

Reviewers: #bitcoin_abc, Fabien

Reviewed By: #bitcoin_abc, Fabien

Differential Revision: https://reviews.bitcoinabc.org/D15490